# Generated by Django 2.0.6 on 2018-06-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_producimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducImage',
            new_name='ProductImage',
        ),
    ]
