# Generated by Django 2.0.6 on 2018-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180618_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media2/products_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
