# Generated by Django 2.0.6 on 2018-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180619_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Http',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_info', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
